
export const Routes = {
    // pages
    Presentation: { path: "/" },
    Login: {path: "/login"},
    CreateUser: {path: "/crear/usuario"},
    DashboardOverview: { path: "/dashboard/overview" },
    EditUser : {path:"/editar/usuario"},
    ReadUser : {path:"/datos/usuario"},
    CreateSede: {path: "/crear/Sede"},
    SearchSede: {path: "/buscar/Sede"},
    ReadSede: {path: "/datos/Sede"},
    EditSede: {path: "/editar/Sede"},
    CreateCourse: {path: "/crear/Curso"},
    SearchCourse: {path: "/buscar/Curso"},
    ReadCourse: {path: "/datos/Curso"},
    EditCourse: {path: "/editar/Curso"},
    CreateGroup: {path: "/crear/Grupo"},
    SearchGroup: {path: "/buscar/Grupo"},
    ReadGroup: {path: "/datos/Grupo"},
    EditGroup: {path: "/editar/Grupo"},
    SearchMemUsr: {path: "/buscar/membresia/usr"},
    ReadMemxUsr: {path: "/datos/membresia/usr"},
    SearchMembresia: {path: "/buscar/membresia"},
    ReadMembresia: {path: "/datos/membresia"},
    CreateMembresia: {path: "/crear/membresia"},
    EditMembresia: {path: "/editar/membresia"},
    AsignarMembresia: {path: "/asignar/membresia"},


    Transactions: { path: "/transactions" },
    Settings: { path: "/settings" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/examples/sign-in" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset-password" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" }
};